import Head from "next/head";
import React, { useEffect } from "react";
import Navbar from "src/components/Navbar";
import { useAppDispatch } from "src/hooks/redux";
import {
  modeSchema,
  type Mode,
  reset,
  stateShema,
  mount,
  initialize,
  switchMode,
  addSeed,
} from "src/store/metaSlice";
import {} from "src/store/metaSlice";

interface LayoutProps {
  children: React.ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  const dispatch = useAppDispatch();

  useEffect(() => {
    initialization(dispatch);
    dispatch(mount());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Rasli</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <main className="px-2">{children}</main>
    </>
  );
}

function initialization(dispatch: ReturnType<typeof useAppDispatch>) {
  //meta
  initState("comfy", dispatch);
  initState("unlimited", dispatch);
  // Mode
  const modeRaw = localStorage.getItem("mode");
  const parsedMode = modeSchema.safeParse(modeRaw);
  if (parsedMode.success) {
    dispatch(switchMode(parsedMode.data));
  }
  // seed
  const seed = localStorage.getItem("seed") ?? Math.random().toString();
  dispatch(addSeed(seed));
}

function initState(mode: Mode, dispatch: ReturnType<typeof useAppDispatch>) {
  const stateRaw = localStorage.getItem(mode);
  if (stateRaw !== null) {
    const stateJson: unknown = JSON.parse(stateRaw);
    const parsed = stateShema.safeParse(stateJson);
    if (parsed.success) {
      dispatch(initialize({ mode: mode, state: parsed.data }));
    } else {
      dispatch(reset(mode));
    }
  } else {
    dispatch(reset(mode));
  }
}
